In [1]:
%pip install --user pandas
import pandas as pd
df_docs = pd.read_csv("/scratch/aa5f25/datasets/paper/paper_docs.csv", sep=";")
df_docs

Requirement already satisfied: pandas in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages
Requirement already satisfied: numpy>=1.15.4 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: python-dateutil>=2.7.3 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: pytz>=2017.2 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas)
Note: you may need to restart the kernel to use updated packages.

,embedding,rand_int,query_label
0,"0.2629320025444031,-0.22875100374221802,-0.104...",11,-1
1,"0.30364999175071716,-0.19963900744915009,-0.09...",2,-1
2,"0.2946319878101349,-0.25989100337028503,-0.178...",1,-1
3,"0.26827698945999146,-0.10750100016593933,-0.13...",12,-1
4,"0.27969199419021606,-0.15651899576187134,-0.18...",5,-1
...,...,...,...
2029992,"0.21286900341510773,-0.10654100030660629,-0.08...",12,-1
2029993,"0.2582069933414459,-0.1930209994316101,-0.1495...",8,-1
2029994,"0.22436200082302094,-0.15109199285507202,-0.18...",3,-1
2029995,"0.23794099688529968,-0.07481200248003006,-0.08...",8,-1
2029996,"0.17699599266052246,-0.21894900500774384,-0.11...",7,-1

In [5]:
# Source - https://stackoverflow.com/a/18145399
# Posted by LondonRob, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-03, License - CC BY-SA 4.0

df_docs= df_docs.drop('query_label', axis=1)

In [6]:
df_docs

                                                 embedding  rand_int
0        0.2629320025444031,-0.22875100374221802,-0.104...        11
1        0.30364999175071716,-0.19963900744915009,-0.09...         2
2        0.2946319878101349,-0.25989100337028503,-0.178...         1
3        0.26827698945999146,-0.10750100016593933,-0.13...        12
4        0.27969199419021606,-0.15651899576187134,-0.18...         5
...                                                    ...       ...
2029992  0.21286900341510773,-0.10654100030660629,-0.08...        12
2029993  0.2582069933414459,-0.1930209994316101,-0.1495...         8
2029994  0.22436200082302094,-0.15109199285507202,-0.18...         3
2029995  0.23794099688529968,-0.07481200248003006,-0.08...         8
2029996  0.17699599266052246,-0.21894900500774384,-0.11...         7

[2029997 rows x 2 columns]

In [8]:
df_queries = pd.read_csv("/scratch/aa5f25/datasets/paper/paper_queries.csv", sep=";")
df_queries

                                              embedding  rand_int  query_label
0     0.18394100666046143,-0.0625929981470108,-0.108...        11            0
1     0.20332999527454376,-0.09437700361013412,-0.10...         2            1
2     0.11066299676895142,-0.044043999165296555,-0.0...         1            2
3     0.24615100026130676,-0.10814200341701508,-0.00...        12            3
4     0.32651498913764954,-0.16267600655555725,-0.10...         5            4
...                                                 ...       ...          ...
9995  0.17453999817371368,-0.16027599573135376,-0.05...         7         9995
9996  0.16341200470924377,-0.13118599355220795,-0.01...         2         9996
9997  0.1755719929933548,-0.21993699669837952,-0.085...         4         9997
9998  0.17396600544452667,-0.06954299658536911,-0.08...         8         9998
9999  0.2477409988641739,-0.11929599940776825,-0.126...        11         9999

[10000 rows x 3 columns]

In [9]:
df_queries= df_queries.drop('query_label', axis=1)

In [10]:
df_queries

                                              embedding  rand_int
0     0.18394100666046143,-0.0625929981470108,-0.108...        11
1     0.20332999527454376,-0.09437700361013412,-0.10...         2
2     0.11066299676895142,-0.044043999165296555,-0.0...         1
3     0.24615100026130676,-0.10814200341701508,-0.00...        12
4     0.32651498913764954,-0.16267600655555725,-0.10...         5
...                                                 ...       ...
9995  0.17453999817371368,-0.16027599573135376,-0.05...         7
9996  0.16341200470924377,-0.13118599355220795,-0.01...         2
9997  0.1755719929933548,-0.21993699669837952,-0.085...         4
9998  0.17396600544452667,-0.06954299658536911,-0.08...         8
9999  0.2477409988641739,-0.11929599940776825,-0.126...        11

[10000 rows x 2 columns]

In [12]:
df_docs

                                                 embedding  rand_int
0        0.2629320025444031,-0.22875100374221802,-0.104...        11
1        0.30364999175071716,-0.19963900744915009,-0.09...         2
2        0.2946319878101349,-0.25989100337028503,-0.178...         1
3        0.26827698945999146,-0.10750100016593933,-0.13...        12
4        0.27969199419021606,-0.15651899576187134,-0.18...         5
...                                                    ...       ...
2029992  0.21286900341510773,-0.10654100030660629,-0.08...        12
2029993  0.2582069933414459,-0.1930209994316101,-0.1495...         8
2029994  0.22436200082302094,-0.15109199285507202,-0.18...         3
2029995  0.23794099688529968,-0.07481200248003006,-0.08...         8
2029996  0.17699599266052246,-0.21894900500774384,-0.11...         7

[2029997 rows x 2 columns]

In [13]:
df_queries["query_attribute"] = range(1, len(df_queries) + 1)

In [14]:
df_queries

,embedding,rand_int,query_attribute
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,1
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,2
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,3
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,4
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,5
...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,9996
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,9997
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,9998
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,9999
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,10000

In [ ]:
import numpy as np

# ensure column exists
if "query_attr" not in df_docs.columns:
    df_docs["query_attribute"] = ""

N = len(df_docs)
selectivity = 0.10
target = int(selectivity * N)

# reset index to be safe
df_docs = df_docs.reset_index(drop=True)

for _, row in df_queries.iterrows():
    query_value = str(row["query_attribute"])   # column name in df_queries
    
    # randomly select target rows
    indices = np.random.choice(df_docs.index, target, replace=False)
    
    for idx in indices:
        if df_docs.at[idx, "query_attr"] == "":
            df_docs.at[idx, "query_attr"] = query_value
        else:
            df_docs.at[idx, "query_attr"] += "," + query_value

In [26]:
df_queries1

                                             embedding  correlation
0    -0.3205789,0.06644345,0.22195277,-0.13523898,-...            0
1    -0.2833061,-0.13634399,0.38554284,-0.28529945,...            1
2    0.03552235,0.31721422,0.2561202,0.060554873,0....            2
3    0.1314554,0.31659058,0.0035175257,-0.17587781,...            3
4    -0.36439136,0.07383215,0.3017879,-0.2734844,0....            4
..                                                 ...          ...
995  0.15833698,-0.03161161,0.71027946,0.032480977,...          995
996  0.027496073,-0.10356202,0.76896113,-0.19816184...          996
997  -0.10130168,-0.08833368,-0.10891157,-0.2263839...          997
998  0.0006294999,-0.3083132,0.61100656,-0.12058302...          998
999  0.00072121306,-0.02960684,0.40997794,-0.037810...          999

[1000 rows x 2 columns]

In [17]:
df2 = df[["embedding", "correlation_files"]]

In [18]:
df2

                                                embedding correlation_files
0       -0.3425868,0.32548454,0.4870531,-0.37503994,-0...                -1
1       -0.11744792,-0.19202681,0.50087184,-0.16649805...                -1
2       -0.19148643,0.0009214283,0.34294525,-0.3131651...                -1
3       -0.27164686,0.07948127,0.39479753,-0.5501128,-...                -1
4       -0.1501147,0.26418093,0.4900402,-0.41568285,-0...                -1
...                                                   ...               ...
813481  -0.004253374,-0.05755319,0.42041805,-0.3706104...                -1
813482  -0.19087975,-0.18493585,0.6684668,-0.16273195,...                -1
813483  -0.0339704,-0.059509445,0.57890916,-0.52386916...                -1
813484  -0.10159028,-0.17919351,0.53581035,-0.3646105,...                -1
813485  -0.080517,0.14794855,0.5342876,-0.3118318,-0.0...                -1

[813486 rows x 2 columns]

In [28]:
import numpy as np
df["value_20"] = np.where(
    np.random.rand(len(df)) < 0.2,
    1,
    np.random.randint(2, 13, size=len(df))
)

In [29]:
df

,embedding,rand_int,value_90,value_80,value_60,value_40,value_20
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,1,7,1,1,4
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,1,1,1,12,7
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,1,1,1,4,6
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,1,1,1,1,8
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,1,1,7,1,5
...,...,...,...,...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,1,1,1,1,12
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,1,1,1,2,5
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,1,1,1,1,11
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,8,9,2,1,1
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,1,3,5,8,11

In [ ]:
import re

text = """
Search Time for efSearch=10 => Total Queries: 10000, Total Time: 7.17226s, QPS: 1394.26
Search Time for efSearch=20 => Total Queries: 10000, Total Time: 7.55264s, QPS: 1324.04
Search Time for efSearch=60 => Total Queries: 10000, Total Time: 6.84534s, QPS: 1460.85
Search Time for efSearch=200 => Total Queries: 10000, Total Time: 7.39231s, QPS: 1352.76
Search Time for efSearch=400 => Total Queries: 10000, Total Time: 8.15789s, QPS: 1225.81
Search Time for efSearch=800 => Total Queries: 10000, Total Time: 9.87495s, QPS: 1012.66
Search Time for efSearch=1000 => Total Queries: 10000, Total Time: 13.428s, QPS: 744.712
Search Time for efSearch=1200 => Total Queries: 10000, Total Time: 16.016s, QPS: 624.374
Search Time for efSearch=1300 => Total Queries: 10000, Total Time: 12.3775s, QPS: 807.92





"""

# Extract QPS values using regex
qps_values = re.findall(r"QPS:\s*([\d\.]+)", text)

# Convert strings to float
qps_array = [float(q) for q in qps_values]

print(qps_array)

[544.787, 539.151, 554.301, 555.239, 584.74, 591.352, 556.783, 579.58, 595.497]

In [34]:
df["value_80"].value_counts(normalize=True) * 100

1     79.21
3      2.11
5      2.03
10     1.98
11     1.97
7      1.87
12     1.87
8      1.86
9      1.85
4      1.80
2      1.74
6      1.71
Name: value_80, dtype: float64

In [ ]:
column_name = "random_value"

# 1️⃣ Count frequency of each unique value
freq_counts = df[column_name].value_counts().sort_index()
print("Counts:")
print(freq_counts)

# 2️⃣ Convert to percentage
freq_percent = df[column_name].value_counts(normalize=True).sort_index() * 100
print("\nPercentages:")
print(freq_percent)

# 3️⃣ Combine into a single DataFrame for easy view / export
verification_df = pd.DataFrame({
    "random_value": freq_counts.index,
    "count": freq_counts.values,
    "percentage": freq_percent.values
})

print("\nVerification table:")
print(verification_df)

In [21]:
import random
from collections import Counter
import pandas as pd

TOTAL = 10000
data = []

# Fixed counts for 1–4
data.extend([1] * 2950)
data.extend([2] * 1972)
data.extend([3] * 1479)
data.extend([4] * 986)

# Remaining rows for 5–12
remaining = TOTAL - len(data)  # 2,613
values_5_to_12 = list(range(5, 13))  # 8 numbers
per_value = remaining // len(values_5_to_12)  # 326
extra = remaining % len(values_5_to_12)       # 5 leftover rows

for i, v in enumerate(values_5_to_12):
    count = per_value + (1 if i < extra else 0)  # distribute leftover
    data.extend([v] * count)

# Shuffle
random.shuffle(data)

# Load into pandas
df_random_items = pd.DataFrame(data, columns=["random_value"])

# Verification
print("Total rows:", len(df_random_items))  # Should be 10,000
print(Counter(df_random_items["random_value"]))

Total rows: 10000
Counter({1: 2950, 2: 1972, 3: 1479, 4: 986, 8: 327, 5: 327, 9: 327, 6: 327, 7: 327, 11: 326, 12: 326, 10: 326})

In [22]:
df_random_items

      random_value
0                2
1                2
2                3
3                4
4               11
...            ...
9995             4
9996             6
9997             2
9998             2
9999             7

[10000 rows x 1 columns]

In [23]:
assert len(df) == len(df_random_items), "DataFrames must have the same length!"

# Add the column
df["random_value"] = df_random_items["random_value"]
df

,embedding,rand_int,random_value
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,2
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,2
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,3
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,4
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,11
...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,4
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,6
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,2
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,2
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,7

In [24]:
df.to_csv("/home/aa5f25/Dataset/data/hnsw/paper/paper_queries.csv", index=False, sep=";")

In [3]:
import pandas as pd
df = pd.read_csv("/scratch/aa5f25/datasets/paper/paper_docs.csv", sep=";")
df

                                                 embedding  rand_int
0        0.2629320025444031,-0.22875100374221802,-0.104...        11
1        0.30364999175071716,-0.19963900744915009,-0.09...         2
2        0.2946319878101349,-0.25989100337028503,-0.178...         1
3        0.26827698945999146,-0.10750100016593933,-0.13...        12
4        0.27969199419021606,-0.15651899576187134,-0.18...         5
...                                                    ...       ...
2029992  0.21286900341510773,-0.10654100030660629,-0.08...        12
2029993  0.2582069933414459,-0.1930209994316101,-0.1495...         8
2029994  0.22436200082302094,-0.15109199285507202,-0.18...         3
2029995  0.23794099688529968,-0.07481200248003006,-0.08...         8
2029996  0.17699599266052246,-0.21894900500774384,-0.11...         7

[2029997 rows x 2 columns]

In [30]:
import os
import pandas as pd

# Example: load your dataframe
# df = pd.read_csv("your_dataset.csv")
# Make sure index matches those numbers
# df.index = df.index.astype(int)
df = pd.read_csv("/scratch/aa5f25/datasets/TripClick/documents_full.csv", sep=";")


folder_path = "/scratch/aa5f25/datasets/TripClick/Corelation"  # <-- your folder path

# Create empty column
df["correlation_files"] = ""

for file in os.listdir(folder_path):
    if not file.endswith(".csv"):
        continue

    file_path = os.path.join(folder_path, file)

    # Read the single-line file
    with open(file_path, "r") as f:
        line = f.readline().strip()

    if not line:
        continue

    # Split left and right
    key, idx_string = line.split(";")

    # Convert index positions to list of integers
    indices = list(map(int, idx_string.split(",")))

    # Keep only valid indices (avoid crash if bad index exists)
    valid_indices = [i for i in indices if i in df.index]

    # Update dataframe
    for idx in valid_indices:
        if df.at[idx, "correlation_files"] == "":
            df.at[idx, "correlation_files"] = key
        else:
            df.at[idx, "correlation_files"] += f",{key}"

print("Done processing all files.")

Done processing all files.

In [31]:
df

,DateCreated,ClinicalAreas,embedding,correlation_files
0,2020-02-23,Gastroenterology,"-0.3425868,0.32548454,0.4870531,-0.37503994,-0...",
1,2020-02-23,Gastroenterology,"-0.11744792,-0.19202681,0.50087184,-0.16649805...",
2,2020-02-23,Gastroenterology,"-0.19148643,0.0009214283,0.34294525,-0.3131651...",
3,2020-02-23,Gastroenterology,"-0.27164686,0.07948127,0.39479753,-0.5501128,-...",
4,2020-02-23,Gastroenterology,"-0.1501147,0.26418093,0.4900402,-0.41568285,-0...",
...,...,...,...,...
813481,2020-09-29,Geriatrics,"-0.004253374,-0.05755319,0.42041805,-0.3706104...",
813482,2020-09-29,Geriatrics,"-0.19087975,-0.18493585,0.6684668,-0.16273195,...",
813483,2020-09-29,Geriatrics,"-0.0339704,-0.059509445,0.57890916,-0.52386916...",
813484,2020-09-29,Geriatrics,"-0.10159028,-0.17919351,0.53581035,-0.3646105,...",
813485,2020-09-29,Geriatrics,"-0.080517,0.14794855,0.5342876,-0.3118318,-0.0...",

In [32]:
df1= df[['embedding', 'correlation_files']]

In [33]:
df1

                                                embedding correlation_files
0       -0.3425868,0.32548454,0.4870531,-0.37503994,-0...
1       -0.11744792,-0.19202681,0.50087184,-0.16649805...
2       -0.19148643,0.0009214283,0.34294525,-0.3131651...
3       -0.27164686,0.07948127,0.39479753,-0.5501128,-...
4       -0.1501147,0.26418093,0.4900402,-0.41568285,-0...
...                                                   ...               ...
813481  -0.004253374,-0.05755319,0.42041805,-0.3706104...
813482  -0.19087975,-0.18493585,0.6684668,-0.16273195,...
813483  -0.0339704,-0.059509445,0.57890916,-0.52386916...
813484  -0.10159028,-0.17919351,0.53581035,-0.3646105,...
813485  -0.080517,0.14794855,0.5342876,-0.3118318,-0.0...

[813486 rows x 2 columns]

In [8]:
print(df1.loc[710264])

embedding            0.076131254,0.32869706,-0.26396635,0.46133634,...
correlation_files    537,949,743,213,592,77,395,428,870,174,800,78,...
Name: 710264, dtype: object

In [10]:
df1["correlation_files"] = df1["correlation_files"].fillna(-1)

/home/aa5f25/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df1.to_csv("/scratch/aa5f25/datasets/TripClick/TripClick_queries_with_correlation.csv", index=False, sep=";")